spring.application.name=eurosporthub-api

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

app.euro.competition-id=387
app.euro.season=2024
app.euro.default-group-id=${EURO_DEFAULT_GROUP_ID}
app.euro.team-logo-base-url=${TEAM_LOGO_BASE_URL}
app.livescore.api-base-url=${LIVE_SCORE_API_BASE_URL}
app.web-origin=${WEB_ORIGIN}