spring.application.name=eurosporthub-api

spring.data.mongodb.uri=mongodb://localhost:27017/Eurodb
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

app.euro.competition-id=387
app.euro.season=2024
app.euro.default-group-id=2763
app.web-origin=http://localhost:3000